TarakanovaD-task01
iu4-org/iu4-2k22-is pull request #10
Opened 2022-03-05 12:01 UTC by TarakanovaDaria

2022-03-05 13:18 UTC, Toliak requested changes
Вижу только `strstr` в коммитах. Можете уточнить, будут ли решения других задач?

2022-03-05 13:18 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +	cmp byte[r9], byte[r9]		; if *(uint8_t*)r9 == 0 <==> zf == 1
1. Такой команды не существует. Проверять отдельные команды "на существование" можно [здесь](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=cmp+byte%5Br9%5D%2C+byte%5Br9%5D&arch=x86-64&as_format=inline#assembly).
Обычно для таких случаев используют какой-нибудь регистр, например
```
mov r8b, byte [r9]
test r8b, r8b
```

2. Если принять, что такая команда возможна, то ZF будет всегда 1.
`cmp` выполняет вычитание (т.е. `cmp a, b` это `update_flags(a - b)`); а `test` выполняет бинарное И.
Подробнее можно посмотреть [про CMP](https://c9x.me/x86/html/file_module_x86_id_35.html) и [про TEST](https://c9x.me/x86/html/file_module_x86_id_315.html). Или, в крайнем случае, в доке интела

2022-03-05 13:18 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +; char *strstr(const char *haystack, const char *needle);
Необычный нейминг аргументов :)

2022-03-05 13:18 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +	pop rbx, r9 				; <restore rbx, r9>
Что здесь имелось в виду?..
`r9` восстанавливать не надо, он volatile согласно [выбранному Calling Convention'у](https://en.wikipedia.org/wiki/X86_calling_conventions#Microsoft_x64_calling_convention)

2022-03-05 13:18 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +	jnz matched					; goto matched; else
jnz сработает тогда, когда [rbx] и [r9] не совпали. Это точно ожидалось именно так?
Для проверки на "совпадение" и "несовпадение" лучше использовать `je` или `jne`. Они [эквивалентны](http://www.unixwiz.net/techtips/x86-jumps.html) `jz` и `jnz` (соответственно), но еще позволяют понять, что хотел сказать автор

2022-03-05 13:18 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +	test byte[rbx], byte[rbx] 	; if *(uint8_t*)rbx != 0 <==> zf != 1
Если я правильно распознал алгоритм, то на данной строке проверяется случай "во время проверки подстроки (иголки) закончился стог сена".
И, если стог сена закончился, то выполнится 32-я строка и функция вернет `rax = rcx = rbx`. Но ведь подстрока не была найдена, то есть ожидался `0` в возврате...

2022-03-05 13:18 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +	test byte[rbx], byte[rbx] 	; if *(uint8_t*)rbx != 0 <==> zf != 1
Пусть функция вызывается как `strstr("aab", "ab")`
Ожидается, что вернется указатель на 2й символ строки "aab".
Мне кажется, что в написанном коде оно не вернется, потому что:
```
1 шаг (ok, matched):
aab
^
ab
^

2 шаг (ok, unmatched):
aab
 ^
ab
 ^

3 шаг (не ок, нужно было отступить назад):
aab
  ^
ab
^
```
Если это действительно так, то можно решить с использованием еще одного регистра, в который сохранять `rbx` если matched и восстанавливать, если unmatched.

2022-03-06 00:19 UTC, Toliak commented on Tarakanova_D/task01/strnlen.asm
> +	push rbx, r8
[Такой команды не существует](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=push+rbx%2C+r8&arch=x86-64&as_format=inline#assembly)

Возможно имелось в виду:
```
push rbx
push r8
```

P.S. по Microsoft Calling Convention x64 -- r8 регистр -- volatile, т.е. его сохранять не нужно

2022-03-06 18:17 UTC, Toliak requested changes
- По checksum: один критичный момент
- По strncpy: можно не править, но тогда нужно ответить, правильно ли я понял авторскую задумку в отмеченных местах
- По strnlen: можно не править, но тогда нужно ответить, правильно ли я понял авторскую задумку в отмеченном месте
- По strstr: пока что не увидел изменений... там все еще есть места, которые желательно исправить и есть другие места, на которые можно просто ответить

2022-03-06 18:17 UTC, Toliak commented on Tarakanova_D/task01/chksum.asm
> +	mov rax, r9				; return r9
(Прям критично) По условию нужен `int`, а он 32 бита. 32-битный регистр это `eax`
Аналогично про r8 (нужен будет `r8d`) и про r9 (нужен будет `r9d`).

2022-03-06 18:17 UTC, Toliak commented on Tarakanova_D/task01/chksum.asm
> +	mov r8, byte [rbx] 		; r8 = *(uint8_t*)rbx
Лучше `movzx r8d, byte [rbx]`. Он занулит весь r8d (32 бита), перед тем, как класть в него 8 бит.
(Почему именно `r8d` -- ниже)

2022-03-06 18:17 UTC, Toliak commented on Tarakanova_D/task01/strncry.asm
> +	jnz exit1					; if (r9 == r8) goto exit1
😅 Можете пояснить, что тут планировалось сделать?
Выглядит как будто из "dest" вычитается "src"...  Возможно, имелось в виду:
```asm
mov r9, r10     ; Смещенный указатель на src
sub r9, rdx      ; Базовый указатель на src
```

2022-03-06 18:17 UTC, Toliak commented on Tarakanova_D/task01/strncry.asm
> +	cmp r9, r8					; r9 <> r8
`rbx` это смещенный указатель на `dest`, так?
`rdx`  это базовый указатель на `src`, верно?
Вопрос: что происходит... 😅

Возможно, имелось в виду:
```asm
mov r9, rbx     ; Смещенный указатель на dest
sub r9, rcx      ; Базовый указатель на dest
```

2022-03-06 18:17 UTC, Toliak commented on Tarakanova_D/task01/strnlen.asm
> +	sub r8, rcx					; r8 = r8 - rcx
`rbx` это смещенный указатель на строку `s`, верно?
`rdx` это счетчик..
Складывается впечатление, что пришел злобный маг 🧙‍♂️ и поменял строчки (cmp и sub) местами...

2022-03-06 18:34 UTC, TarakanovaDaria commented on Tarakanova_D/task01/strncry.asm
> +	jnz exit1					; if (r9 == r8) goto exit1
Действительно. Недоглядела при исправлении.

2022-03-06 18:36 UTC, TarakanovaDaria commented on Tarakanova_D/task01/strnlen.asm
> +	sub r8, rcx					; r8 = r8 - rcx
Ошибка мерджа, исправлю.

2022-03-06 21:05 UTC, Toliak requested changes
Остались 3 мельчайших фикса

2022-03-06 21:05 UTC, Toliak commented on Tarakanova_D/task01/chksum.asm
> +	sub rdx, 1 				; rdx -= 1
`size` тоже `int` , то есть ожидается `edx`

2022-03-06 21:05 UTC, Toliak commented on Tarakanova_D/task01/strncry.asm
> +	jmp loop1					; goto loop1
Внутри этого цикла не меняется ни r10, ни rdx. Либо цикл будет бесконечным, либо я что-то упускаю...

[Предыдущий комментарий](https://github.com/xthebat/iu4-2k22-is/pull/10#discussion_r820267796)

2022-03-06 21:05 UTC, Toliak commented on Tarakanova_D/task01/strstr.asm
> +	test r9, r9					; if *(uint8_t*)rdx == 0 <==> zf == 1
В данном случае будет сравниваться указатель, а, кажется, ожидалось сравнение разыменованного указателя...

2022-03-07 00:08 UTC, Toliak reviewed
Все норм
Посмотрите комментарии, там один вопрос (пропустил крайний случай в chksum при предыдущей проверке :c )
Можете перетаскивать в `task02` директорию и менять целевую ветку мержа на `task01`

2022-03-07 00:08 UTC, Toliak commented on Tarakanova_D/task01/chksum.asm
> +	jz loop 				; if (zf == 0) goto loop
И тут я понял, что в прошлом ревью забыл проверить случай, когда `size = 0` при вызове функции.
Можете просто написать ответом на этот комментарий, как бы решили проблему. Или исправить код, если так удобнее

2022-03-07 00:08 UTC, Toliak commented on Tarakanova_D/task01/strncry.asm
> +	add r10, 1 					; (uint8_t*)r10 += 1
Интересный способ, продолжить использовать указатель, но не доставать из него данные
Утром еще разок гляну, всё ли тут в порядке. Но так вроде ок..

Название файла strn**cry** (неожиданная опечатка 😭) так и планировалось?)

2022-03-07 08:49 UTC, TarakanovaDaria commented on Tarakanova_D/task01/strncry.asm
> +	add r10, 1 					; (uint8_t*)r10 += 1
Мое душевное состояние при работе с ассемблером)

2022-03-07 09:18 UTC, TarakanovaDaria commented on Tarakanova_D/task01/chksum.asm
> +	jz loop 				; if (zf == 0) goto loop
Немного исправила код. Проверка проводится перед `loop`, в случае `size = 0` сразу переходим на `exit`. Так как функция должна выдать `int`, предварительно присваиваем нуль `r9d`.

2022-03-07 09:27 UTC, Toliak reviewed
Все в порядке. Остались "организационные пляски" с директорией и гитом

2022-03-07 12:07 UTC, closed without merging