Liber_task01
iu4-org/iu4-2k22-is pull request #12
Opened 2022-03-05 17:50 UTC by hhakal

2022-03-05 19:10 UTC, Toliak requested changes
Некоторые комментарии пометил как "не критичные", их исправлять не обязательно.
Если я где-то ошибся или что-то не увидел -- можете писать ответом на соответствующие комментарии

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +	cmp byte[rbx], byte[r10]    ;if (*rbx==*r10)
К сожалению, такой команды не существует. Проверить можно [здесь](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=cmp+byte%5Brbx%5D%2C+byte%5Br10%5D&arch=x86-64&as_format=inline#assembly)
Возможный фикс: мысленно зарезервировать 2 регистра, и в них через `mov r8b, byte [rbx]` (на примере `r8b = *rbx`) класть. Главное помнить, что destination register должен быть 8-битный.

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +; char * strstr( const char * string1, const char * string2 );
(не критично) Названия аргументов не отражают сути происходящего и трудно понять, что хотел сказать автор.
Буду предполагать, что в строке `string1` производится поиск подстроки `string2`.

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +	jz match					;if (*rbx==*r10) goto match
Что произойдет, если `string1` будет длиннее, чем `string2`? Кажется, будет выход за границу строки `string1`...

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +	add rbx,1					;rbx+=1
Посмотрел код ниже и понял, что сюда мы не попадаем, если в процессе проверки подстроки произошел unmatch.

В любом случае советую посмотреть [Пошаговый примерчик для другого случая](https://github.com/xthebat/iu4-2k22-is/pull/10#discussion_r820101161), чтобы при исправлении учесть этот случай.

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +	mov rax, 0					;return 0
После этой команды оно пойдет дальше (ниже). Это точно было запланировано?
(Если предположить, что перешли с 12-й строки, то прохождение ниже будет обращаться за пределы строки `string1`)
(А если предположить, что перешли с 25-й строки, то вроде все нормально....)

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strcpy.asm
> +	jz exit				;(if r8==0) goto exit
Прыгаем на exit, там делаем pop и... стек сломан, т.к. push'а не было

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strcpy.asm
> +	add rbx, 1			;rbx+=1
Двойное вычитание из `r8` будет (13 строка и 24)
[Подробно и с примером здесь](https://github.com/xthebat/iu4-2k22-is/pull/7/files/a0b8d93dcb8214c53ced17eed1832305ccba3641#r820065412)

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strnlen.asm
> +	test r10, r10
А если `strnlen("asdas", 0)` будет вызвано?
На самой первой итерции: `r10 (= rdx = 0) - 1` будет `= 0xFFFFFFFF_FFFFFFFF`

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +	jnz no_match				;if (*rbx!=*r10) goto no_match
Так оно же не сбросит `r10`. То есть, например, случай с `string1 = aaaaaaamogus; string2 = amogus` должен вернуть (из функции) указатель (т.к. подстрока есть в строке), а вернет (из функции) `0`

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strstr.asm
> +	mov rax, r11				;return r11
Теперь действие 17-й строки кажется полностью бесполезным...

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/strnlen.asm
> +	mov rax, rdx  			;return rdx
```c
rbx = rbx - (rcx + 1);    // ok, в rbx теперь лежит длина
rax = rcx     // а почему именно rcx, ну ладно
pop(rbx);      // так стоп а зачем мы тогда клали длину в rbx, мы ведь теперь её перетерли
rax = rdx     // я перестал понимать происходящее
```

Поясню, `mov rax, значение` это не тоже самое, что и return.
return это, скорее (на примере `return rbx`):
```asm
mov rax, rbx
pop ... ; восстанавливаем non-volatile регистры через pop
ret
```

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/chksum.asm
> +	add r10, byte [rbx] 	;r10 += *rbx
1. Такой команды [не существует](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=add+r10%2C+byte+%5Brbx%5D&arch=x86-64&as_format=inline#assembly). Нужно использовать какой-нибудь регистр, чтобы в него положить `byte [rbx]`
2. Вероятно, был пропущен сброс регистра r10 (`xor r10, r10`) в начале функции

2022-03-05 19:10 UTC, Toliak commented on Liber_Y/task01/chksum.asm
> +	test rdx, rdx
А если в функцию передали `size = 0`? 
Тогда на первой итерации будет `rdx - 1 = 0 - 1 = 0xFFFFFFFF_FFFFFFFF`

2022-03-06 19:51 UTC, Toliak requested changes
- `strncpy`:
  -  Файл называется `strcpy`, а не `strncpy`
  - Мелкий фикс
- `strnlen`: переделывать ничего не надо
  - В целом алгоритм "сначала считаем длину всей строки, потом берем то значение, которое меньше" может существовать, но есть один случай, который его ломат: если была передана "сломанная" строка, которая не имеет в конце '\0` символ-терминатор
  - Также есть несколько комментариев внутри review, рекомендую почитать
- `strstr`: небольшой фикс required

Остальное принято

Кажется файлы из директори `task01` не были удалены...
Плюс проверьте, чтобы мерж был в ветку `task02`. Если возникнут вопросы, пишите в ДС.

2022-03-06 19:51 UTC, Toliak commented on Liber_Y/task02/strcpy.asm
> +	jz exit				;if (r8==0) goto exit
Оно ж не pop'нет..

2022-03-06 19:51 UTC, Toliak commented on Liber_Y/task02/strstr.asm
> +	mov r11, rbx				;r11 = rbx
Согласен ✅

2022-03-06 19:51 UTC, Toliak commented on Liber_Y/task02/strstr.asm
> +	sub r10, 1
Не факт, что вычитать нужно именно 1. Давайте лучше сохраним r10 во временный регистр (как это сделано с rbx)

2022-03-06 19:51 UTC, Toliak commented on Liber_Y/task02/strnlen.asm
> +	jge max_len
Лайк за использование этих команд!
Есть один нюанс, не критичный, но о нем стоит помнить.
`jge` применяется тогда, когда нужно сравнить `signed` числа, а счетчик, в данном случае, вроде бы подразумевается как `unsigned`, поэтому лучше использовать `jae`.
[Табличка со всеми переходами](http://www.unixwiz.net/techtips/x86-jumps.html)

2022-03-06 19:51 UTC, Toliak commented on Liber_Y/task02/strnlen.asm
> +	jl exit
(не критично): можно просто `jmp`, оно же в любом случае меньше будет (т.к. не прошло в предыдущее условие)

2022-03-06 20:05 UTC, hhakal commented on Liber_Y/task02/strstr.asm
> +	sub r10, 1
А могу ли я не вычитать 1, а просто mov в r10 rdx, и тем самым вернусь в начало как раз? Без использования доп регистра

2022-03-06 20:06 UTC, hhakal commented on Liber_Y/task02/strstr.asm
> +	sub r10, 1
> Не факт, что вычитать нужно именно 1. Давайте лучше сохраним r10 во временный регистр (как это сделано с rbx)

А могу ли я просто мувнуть в r10 rdx, и тем самым вернусь в начало как раз? Без использования доп регистра

2022-03-06 20:14 UTC, Toliak commented on Liber_Y/task02/strstr.asm
> +	sub r10, 1
Да, так даже лучше

2022-03-06 21:14 UTC, Toliak reviewed
Осталась правка по `strstr` и разобраться с веткой и директориями

2022-03-06 21:22 UTC, Toliak reviewed
Отлично. Все пофикшено
Только я немного не понял, как так получилось, что изменения прыгнули из директории `task02` в `task01`  C:

2022-03-07 14:21 UTC, closed without merging