Labuz_N-task01 (#5)
iu4-org/iu4-2k22-is pull request #8
Opened 2022-03-04 20:24 UTC by NikolayLabuz

2022-03-05 09:41 UTC, Toliak requested changes

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/chksum.asm
> +	add rax, al
`al` это младшая 8-битная часть регистра `rax`.
[Подробнее описал здесь](https://github.com/xthebat/iu4-2k22-is/pull/7#discussion_r820063887)

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strnlen.asm
> +    ret
(не критично): Обычно (компилятор так делает) финал функции уносят под отдельную метку.
[Примерчик](https://github.com/xthebat/iu4-2k22-is/pull/7#discussion_r820067575)

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strnlen.asm
> +	push r10
Согласно [выбранному calling convention'у](https://en.wikipedia.org/wiki/X86_calling_conventions#Microsoft_x64_calling_convention): `The registers RAX, RCX, RDX, R8, R9, R10, R11 are considered volatile (caller-saved)`. То есть `r10` сохранять не надо

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strncpy.asm
> +	sub r8, 1
Если внутри loop r8 будет 1 (а такая итерация точно будет), то на 14 и 18 строке будет двойное вычитание из r8.
Подробнее (пошагово) описал [здесь](https://github.com/xthebat/iu4-2k22-is/pull/7#discussion_r820065412)

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strnlen.asm
> +	test rdx, rdx
`strnlen("qwerty", 1)` точно отработает корректно? (Ожидается, что вернет 1)
[Подробнее здесь описал](https://github.com/xthebat/iu4-2k22-is/pull/7/files/a0b8d93dcb8214c53ced17eed1832305ccba3641#r820066245)

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strnlen.asm
> +	mov rax, r10
Рассмотрим `strnlen("", 100)`. Ожидается, что вернет 0.

```
// loop
al = *rbx;   // = '\0'; ok
rdx -= 1;    // = 99; ok
rbx += 1   // ok
r10 += 1   // = 1
// al == 0 -- да , следовательно, идет на 19 строку
return r10;   
// Вернули 1, а ожидался 0
```

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +	push r11
Аналогичная ситуация с Calling Convention: `r1` сохранять не надо

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +	push r11
Точно не `pop`?)

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +	mov rax,r11
Сначала восстановили `r11` до того состояния, в каком он был до вызова функции и... вернули его.
Было запланировано именно такое поведение?

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +	mov r10, 0
(не критично). Обычно используют `xor rax, rax`, т.к. его скомпилированная версия содержит меньше байт.
Однако компилятор иногда сам оптимизирует, поэтому не критично

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +	add r11, 1
Можете немного прояснить, какая роль у r11?
В начале он не сбрасывается. не является аргументом...

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +    test rbx, rbx
Данная строка проверяет содержимое регистра на 0, а в регистре содержится адрес памяти (указатель на символ).
Возможно, имелась в виду проверка разыменованного значения.

2022-03-05 09:41 UTC, Toliak commented on Labuz_N/task01/strstr.asm
> +	je inner_loop
Был ли рассмотрен случай, когда в процессе проверки `substr` закончилась `str`?
(Например, при вызове функции: `strstr("aboba", "abobaaaaaaaaaaaa")`)

Если рассмотрен, укажите, пожалуйста, на какой строке он выйдет из цикла (я не нашел)

2022-03-05 09:41 UTC, Toliak commented
Некоторые комментарии пометил как "не критичные", их исправлять не обязательно.
Если я где-то ошибся или что-то не увидел -- можете писать ответом на соответствующие комментарии

2022-03-07 14:53 UTC, NikolayLabuz commented
перенес в ветку task02

2022-03-07 14:53 UTC, closed without merging