Task01
iu4-org/iu4-2k22-is pull request #9
Opened 2022-03-05 01:28 UTC by kelbor-khal

Ночные размышления...

2022-03-05 10:23 UTC, Toliak requested changes
Некоторые комментарии пометил как "не критичные", их исправлять не обязательно.
Если я где-то ошибся или что-то не увидел -- можете писать ответом на соответствующие комментарии.

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strnlen.s
> +    add rbx, rcx            ; переход к новому адресу
Тут скорее `add rbx, 1`, иначе на второй итерации будет `rbx = str + 1`, на третьей`rbx = (str + 1) + 2` и т.д.

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strnlen.s
> +    sub rbx, rcx            ; определение количества байт
Оно не сработает корректно из-за того, что `rcx` используется в цикле как счетчик.
Скорее всего ожидалось `offset_str_ptr - original_str_ptr`, а получилось `offset_str_ptr - loop_index`

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strnlen.s
> +    cmp rcx, r14            ; сравнение с заданным значением счетчика
`strnlen("asdasdasd", 0)` корректно отработает?
Рассмотрим:
```c
// loop_strnlen
al = *rbx;    // ok
rcx += 1;    // стало 1 (было 0)
rbx += rcx;  // не ok, описал выше почему. К текущему примеру не относится
// rcx == r14 ?  1 == 0? Нет, значит продолжаем цикл, хотя счетчик уже переполнился...
```

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    push r11
Этих ребят (r9, r10, r11), согласно [Microsoft x64 calling convention](https://en.wikipedia.org/wiki/X86_calling_conventions#Microsoft_x64_calling_convention), сохранять не надо

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    add r8, r9
Мне кажется тут тоже (как и в strnlen) нужно `add r8, 1` (или `inc r8`) делать

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    mov r11, byte [r12]              ; загружаем байт по указателю искомой строки
64-битному регистру нельзя присвоить 8-битное значение.
Здесь и далее (на 30, 34, 38 строке) скорее всего имелось в виду `r10b`, `r11b` (т.е. 8-битная часть соответствующего регистра)

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +; r11 равняется нулю если вся строка прошла проверку
Лайк за комменты 👍

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    add r12, rcx                     ; сдвигаем адрес в искомой строке
Все еще кажется, что здесь нужен `inc rbx` и `inc r12`, т.к. иначе оно будет некорректно шагать

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    mov rax, [ rbx - r9]             ; текущее значение rbx минус длина искомой строки
К сожалению, [такой команды не существует](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=mov+rax%2C+%5Brbx+-+r9%5D&arch=x86-64&as_format=inline#assembly)

Плюс тут скорее всего имелось в виду `(char*)rax = (char*)rbx - (size_t)r9`, а это `lea`, а не `mov`

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    mov r12, rdx                     ; возвращаем к исходному значению
Возвращаться к исходному значению в случае несовпадения символов -- ок, согласен.
Но мы ведь сюда попадем даже если элементы равны (т.е. 42 строка, потом 45 и 46)

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    mov al, byte [r14]      ; загрузка одного байта из источника
`al` это часть `rax`, а в `rax` лежит возвращаемое значение (9 строка). Кажется, функция вернет что-то не то, что ожидалось :)

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    add r14, rcx            ; переход к новому адресу источника
База: `rcx = 0`, `r14 = base_str`.
1-я итерация: `rcx = 1`, `r14 = base_ptr + 1`
2-я итерация: `rcx = 2`, `r14 = (base_ptr + 1) + 2`
3-я итерация: `rcx = 3`, `r14 = ((base_ptr + 1) + 2) + 3`
и т.д.

Возможно, здесь имелось в виду `inc r14`

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    cmp rcx, r8             ; сравнение с заданным значением счетчика
Корректно ли отработает данный участок кода, если при вызове функции был передан `num = 0`?

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    str al, [rbx]           ; загрузка данных по адресу строки назначения
Команды не существует :( Вероятно, подразумевалось `mov byte [rbx], al`

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    str 0, [rbx]            ; загрузка данных по адресу строки назначения
Команды не существует :( Вероятно, подразумевалось `mov byte [rbx], 0`

2022-03-05 10:23 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    add rbx, rcx            ; переход к новому адресу назначения
Аналогичный комментарий, как к 17 строке

2022-03-06 16:30 UTC, Toliak requested changes
Стало лучше, но есть еще мелкие баги, иногда критичные...
Некоторые отметил как "не критично", их исправлять не надо

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    add r8, 1
Откуда тут появился `r8` и какова его цель?

UPD: посмотрел ниже, увидел комментарий
Получается, если я правильно понял, в начале функции был пропущен `mov r8, rdx`

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    push r12
`push rbx` еще нужен (и pop в конце), т.к. он тоже используется и является non-volatile (по calling convention'у Microsoft x64)

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +; function strncpy ( const char * string1, const char * string2 )
(Не критично): я надеюсь, имелось в виду strstr, а не strncpy 😅

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    jz  return_value_ok
(Не критично): работать будет, но зачем так сложно?) Можно же проверить: если `r11b` содержит 0, то искомая строка закончилась

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    cmp r10b, r12                    ; сравнение элементов строк
Возможно имелось в виду `cmp r10b, r11b`

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +;------------ (исправил-3) ------------
Тут точно не должно быть никакого перехода (jmp)?
Если пойти дальше, то оно еще раз прибавит 1 к rbx и начнет `loop_increment` выполнять...

Похоже, что надо прыгать на `loop_check`...

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    lea rax, [ rbx - r9]             ; текущее значение rbx минус длина искомой строки
Давайте все-таки сделаем существующей эту команду следующим образом:
```asm
mov rax, rbx
sub rax, r9
```

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strnlen.s
> +    add rcx, -1             ; вычитание нуль-символа
Кейс с `strnlen("asdasdasd", 0)` упадет на этом месте.
Давайте сделаем на 21-й строке `jz` на 34-ю строку

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/chksum.s
> +    mov eax, r9
`mov eax, r9d`

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/chksum.s
> +    add r9, al              ; прибавляем элемент массива
[Такой команды не существует](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=add+r9%2C+al&arch=x86-64&as_format=inline#assembly)

Здесь надо использоватьть `movzx eax, byte ptr [rbx]` (оно занулит весь (64 бита) регистр, а потом переложит в него 8 бит)
А потом `add r9d, eax` (r9d, т.к. нужно только 32 бита)

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/chksum.s
> +    cmp rcx, rdx            ; сравнение счетчика с количеством элементов массива
По условию должен быть `edx`
И, соответственно, можно `ecx` вместо `rcx` использовать

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    add rbx, rcx            ; переход к новому адресу назначения
Вопрос с тем, что тут нужен `inc rbx` остается открытым

2022-03-06 16:30 UTC, Toliak commented on Filin_IA/task_01/strncpy.s
> +    jmp loop_strncpy        ; переход к началу функции
`jmp filling_zeros` имелось в виду (плюс проверка счетчика)? Иначе оно ведь опять копировать пойдет...

2022-03-06 16:36 UTC, kelbor-khal commented on Filin_IA/task_01/strstr.s
> +;------------ (исправил-3) ------------
Стыдно((

2022-03-06 16:37 UTC, kelbor-khal commented on Filin_IA/task_01/strstr.s
> +    lea rax, [ rbx - r9]             ; текущее значение rbx минус длина искомой строки
а почему lea не будет работать?

2022-03-06 17:11 UTC, Toliak commented
Еще один момент
Переименуйте директорию `task01` в `task02`

2022-03-06 17:25 UTC, Toliak commented on Filin_IA/task_01/strstr.s
> +    lea rax, [ rbx - r9]             ; текущее значение rbx минус длина искомой строки
[Эта команда не существует](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=lea+rax%2C+%5Brbx+-+r9%5D&arch=x86-64&as_format=inline#assembly)

2022-03-06 18:40 UTC, Toliak requested changes
- `chksum`: один мелкий фикс и будет закрыто
- `strstr`: один момент с логикой. Есть два варианта: пофиксить код; либо прям код не фиксить (все таки задание скорее "познакомиться с ассемблером"), но написать в комментарии возможный вариант решения.

Остальное норм

2022-03-06 18:40 UTC, Toliak commented on Filin_IA/task_02/strstr.s
> +    mov r12, rdx                     ; возвращаем к исходному значению
Есть один неприятный момент
Тут бы еще сделать сброс `rbx`, но не полный сброс, а сброс до того момента, как начали обходить искомую строку.
[Пример случая, на котором сломается без этого сброса](https://github.com/xthebat/iu4-2k22-is/pull/10#discussion_r820101161)

2022-03-06 18:40 UTC, Toliak commented on Filin_IA/task_02/chksum.s
> +    add rcx, 1                 ; инкрементирование счетчика
Упс, счетчик тоже `int` по условию CCC:

2022-03-06 18:40 UTC, Toliak commented on Filin_IA/task_02/chksum.s
> +    xor r9, r9              ; а вдруг там, что-то лежало
(Не критично): Не обязательно сбрасывать весь `r9`, если используется `r9d`. С другой стороны, хуже не станет :)

2022-03-06 19:14 UTC, kelbor-khal commented on Filin_IA/task_02/strstr.s
> +    mov r12, rdx                     ; возвращаем к исходному значению
Каждый раз, когда у нас символы совпадают инкрементируются адреса искомой строки и строки, в которой ищем, а так же счетчик. В момент, когда проверив, какую-то часть строки, выгруженные символы не равны между собой, мы из текущего адреса rbx вычитаем  значение счетчика, потом инкрементируем rbx, а потом сбрасываем счетчик (rcx). Таким образом получается, что мы вернулись к тому моменту, где только начали проверять строку, а потом сдвинули адрес к следующему элементу.

Возможна следующая реализация:
53    sub rbx, rcx
54    add rbx, 1
55    mov r12, rdx
56    mov rcx, 0 
57    jmp loop_check

Вроде так)

2022-03-06 19:57 UTC, Toliak commented on Filin_IA/task_02/strstr.s
> +    mov r12, rdx                     ; возвращаем к исходному значению
Пойдет.
Еще, как вариант, сохранить "значение для восстановления rbx" в какой-нибудь регистр, а, в случае match-fail'а, достать сохраненное значение

2022-03-06 19:59 UTC, Toliak approved these changes
Баллы: 3/3 + 2/2
- `strncpy` +1
- `strnlen` +1
- `strstr` +1
- `chksum` +2

Нужен аппрув баллов от Алексея Алексеевича.

2022-03-06 20:00 UTC, merged